//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chr.Css.WebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public byte[] Nombre { get; set; }
        public byte[] Direccion { get; set; }
        public int IdPerfil { get; set; }
        public string Contrasena { get; set; }
        public string Usuario1 { get; set; }
        public string Correo { get; set; }
        public string NombreUsuario { get; set; }
    }
}
